# Generated by Django 4.0.3 on 2022-03-11 20:08

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to=project.models.catalog_directory_path)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('catalog_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.catalog_service')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('identification', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Traceability_Order_Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('order_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.order_catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.place')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.type_service'),
        ),
        migrations.CreateModel(
            name='Schedule_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('line_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.line_day')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.service')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='type_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.type_place'),
        ),
        migrations.AddField(
            model_name='order_catalog',
            name='user_college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user_college'),
        ),
        migrations.CreateModel(
            name='Image_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=project.models.place_directory_path)),
                ('location', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.place')),
            ],
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.service')),
                ('user_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user_college')),
            ],
        ),
        migrations.AddField(
            model_name='catalog_service',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.service'),
        ),
    ]
