# Generated by Django 4.0.3 on 2022-04-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('user_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user_college')),
            ],
        ),
        migrations.CreateModel(
            name='Traceability_Order_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('order_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.order_service')),
            ],
        ),
        migrations.CreateModel(
            name='User_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.place')),
                ('user_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user_college')),
            ],
        ),
        migrations.RemoveField(
            model_name='order_catalog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order_catalog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order_catalog',
            name='user_college',
        ),
        migrations.DeleteModel(
            name='Traceability_Order_Catalog',
        ),
        migrations.AddField(
            model_name='order_catalog',
            name='order_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.order_service'),
        ),
    ]
